gitea:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  admin:
    existingSecret: gitea-admin-secret
  config:
    server:
      ENABLE_PPROF: true
      ROOT_URL: http://10.8.0.110:3000/
      DOMAIN: 10.8.0.110
    database:
      DB_TYPE: postgres
      SSL_MODE: require
      HOST: gitea-psql
      NAME: gitea
      USER: gitea
      SCHEMA: public
  additionalConfigFromEnvs:
    - name: ENV_TO_INI__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: gitea.gitea-psql.credentials.postgresql.acid.zalan.do
          key: password

postgresql:
  enabled: false

service:
  http:
    annotations:
      metallb.universe.tf/allow-shared-ip: gitea
    type: LoadBalancer
    port: 3000
    loadBalancerIP: 10.8.0.110
  ssh:
    annotations:
      metallb.universe.tf/allow-shared-ip: gitea
    type: LoadBalancer
    port: 22
    loadBalancerIP: 10.8.0.110

persistence:
  enabled: true
