- name: Updating system firmware
  hosts: all
  gather_facts: false
  become: true
  vars:
    ansible_ssh_pipelining: true
  tasks:
    - name: Install fwupd
      ansible.builtin.apt:
        name: fwupd
    - name: Refresh fwupd db
      register: refresh
      ansible.builtin.command:
        cmd: fwupdmgr refresh
      changed_when: refresh.rc == 0
      failed_when: not (refresh.rc == 0 or refresh.rc == 2)
    - name: Install firmware updates
      register: firmware
      notify: Mark system for reboot
      ansible.builtin.command:
        cmd: fwupdmgr update -y
      changed_when: firmware.rc == 0
      failed_when: not (firmware.rc == 0 or firmware.rc == 2)

  handlers:
    - name: Mark system for reboot
      when: firmware.changed
      ansible.builtin.file:
        path: /var/run/reboot-required
        state: touch
        owner: root
        group: root
        mode: "644"
