all:
  children:
    control:
      hosts:
        10.8.0.11:
          node_name: k-c-1
          k0s_service: k0scontroller.service
          lb_servers:
            - 10.8.0.12
            - 10.8.0.13
        10.8.0.12:
          node_name: k-c-2
          k0s_service: k0scontroller.service
          lb_servers:
            - 10.8.0.11
            - 10.8.0.13
        10.8.0.13:
          node_name: k-c-3
          k0s_service: k0scontroller.service
          lb_servers:
            - 10.8.0.11
            - 10.8.0.12
    work:
      hosts:
        10.8.0.21:
          node_name: k-w-a
          k0s_service: k0sworker.service
        10.8.0.22:
          node_name: k-w-b
          k0s_service: k0sworker.service
        10.8.0.23:
          node_name: k-w-c
          k0s_service: k0sworker.service
