- name: Kubernetes LB Config
  hosts: control
  gather_facts: false
  become: true
  tasks:
    - name: Enable nonlocal bind
      ansible.posix.sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: 1
        sysctl_file: /etc/sysctl.d/80-keepalived.conf
        sysctl_set: true
    - name: Install keepalived
      ansible.builtin.apt:
        name: keepalived
    - name: Enable keepalived daemon
      ansible.builtin.service:
        name: keepalived.service
        state: started
        enabled: true
    - name: Update keepalived config file
      notify: Reload keepalived
      ansible.builtin.copy:
        src: keepalived.conf
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: "600"

  handlers:
    - name: Reload keepalived
      ansible.builtin.service:
        name: keepalived.service
        state: reloaded
