- name: Applying OS Configuration Baseline
  hosts: all
  gather_facts: false
  become: true
  serial: 2
  vars:
    ansible_ssh_pipelining: true
  tasks:
    - name: Configure Sudo NoPasswd
      community.general.sudoers:
        name: sudoers-nopasswd
        state: present
        group: sudo
        commands: ALL
        nopassword: true
    - name: Prepare Aptitude
      ansible.builtin.apt:
        autoremove: true
        autoclean: true
        name: aptitude
    - name: Install HWE
      ansible.builtin.apt:
        notify: Mark reboot
        name: linux-generic-hwe-20.04
    - name: Install NFS Tools
      ansible.builtin.apt:
        name: nfs-common
    - name: Install IPVS Tools
      ansible.builtin.apt:
        name: ['ipset', 'ipvsadm']
    - name: Install Fail2Ban
      ansible.builtin.apt:
        name: fail2ban
    - name: Configure fail2ban
      register: fail2ban_jail
      ansible.builtin.copy:
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: "644"
        content: |
          [sshd]
          enabled = true
          port = 22

          [sshd-ddos]
          enabled = true
          port = 22
    - name: Enable and (re)start fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted
        enabled: true
    - name: Disable swap for current boot
      register: swapoff
      changed_when: swapoff.rc != 0
      ansible.builtin.command:
        cmd: swapoff -a
    - name: Disable Swap permenently
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
        replace: '#\1\2\3swap\4'
        backup: true
    - name: Remove swap.img file
      ansible.builtin.file:
        path: /swap.img
        state: absent
    - name: Enable Transparent Huge-Pages in Grub config
      register: grub_config
      notify: Update Grub
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: "^GRUB_CMDLINE_LINUX"
        line: GRUB_CMDLINE_LINUX="transparent_hugepage=always"
    - name: Configuring Sysctl Optimizations
      notify: Mark reboot
      ansible.posix.sysctl:
        name: "{{ item[0] }}"
        value: "{{ item[1] }}"
        sysctl_file: /etc/sysctl.d/20-optimization.conf
        sysctl_set: true
      loop:
        - ["net.ipv4.tcp_slow_start_after_idle", 1]
        - ["net.ipv4.ip_local_port_range", "49152 65535"]
        - ["net.ipv4.tcp_fastopen", 3]
        - ["net.ipv4.tcp_ecn", 1]
        - ["net.ipv4.tcp_sack", 1]
        - ["net.ipv4.tcp_dsack", 1]
        - ["net.core.rmem_default", 16777216]
        - ["net.core.rmem_max", 16777216]
        - ["net.core.somaxconn", 8192]
        - ["net.core.netdev_max_backlog", 16384]
        - ["net.core.wmem_default", 16777216]
        - ["net.core.wmem_max", 16777216]
        - ["net.core.optmem_max", "65536"]
        - ["net.ipv4.tcp_mem", "1638400 1638400 1638400"]
        - ["net.ipv4.tcp_rmem", "4096 87380 16777216"]
        - ["net.ipv4.tcp_wmem", "4096 87380 16777216"]
        - ["net.ipv4.tcp_adv_win_scale", "-1"]
        - ["net.ipv4.tcp_notsent_lowat", "131072"]
        - ["net.ipv4.udp_rmem_min", "8192"]
        - ["net.ipv4.udp_wmem_min", "8192"]
        - ["net.core.default_qdisc", "fq_codel"]
        - ["net.ipv4.tcp_congestion_control", "bbr"]
        - ["net.ipv4.conf.default.rp_filter", "1"]
        - ["net.ipv4.conf.all.rp_filter", "1"]
        - ["net.ipv4.tcp_max_syn_backlog", "2048"]
        - ["net.ipv4.tcp_synack_retries", "2"]
        - ["net.ipv4.tcp_syn_retries", "2"]
        - ["net.ipv4.conf.all.accept_redirects", "0"]
        - ["net.ipv6.conf.all.accept_redirects", "0"]
        - ["net.ipv4.conf.default.accept_redirects", "0"]
        - ["net.ipv6.conf.default.accept_redirects", "0"]
        - ["net.ipv4.conf.all.send_redirects", "0"]
        - ["net.ipv4.conf.default.send_redirects", "0"]
        - ["net.ipv4.conf.all.accept_source_route", "0"]
        - ["net.ipv6.conf.all.accept_source_route", "0"]
        - ["net.ipv4.conf.default.accept_source_route", "0"]
        - ["net.ipv6.conf.default.accept_source_route", "0"]
        - ["kernel.randomize_va_space", "2"]
        - ["net.ipv4.conf.default.log_martians", "1"]
        - ["net.ipv4.conf.all.log_martians", "1"]


  handlers:
    - name: Mark reboot
      ansible.builtin.file:
        path: /var/run/reboot-required
        state: touch
        owner: root
        group: root
        mode: "644"

    - name: Update grub
      notify: Mark reboot
      ansible.builtin.command: nice update-grub2
