- name: Kubernetes Cluster Patching
  hosts: all
  gather_facts: no
  become: true
  serial: 2
  tasks:
    - name: Install needrestart
      apt:
        cache_valid_time: 900
        name: needrestart
    - name: Update Apt Packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
    - name: Check if service restart is required
      command: "needrestart -p"
      ignore_errors: true
      register: checkrestart
    - name: Mark reboot
      when: checkrestart.failed or sysctl.changed
      file:
        path: /var/run/reboot-required
        state: touch
