- name: Kubernetes Cluster Patching
  hosts: all
  gather_facts: no
  become: true
  order: shuffle
  serial: 1
  tasks:
    - name: Install needrestart
      apt:
        cache_valid_time: 900
        name: needrestart
    - name: Update Apt Packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: Check if service restart is required
      command: 'needrestart -p'
      register: needrestart
      ignore_errors: true
    - name: Drain, Reboot and Uncordon Node
      when: reboot_required.stat.exists or needrestart.failed
      block:
      - name: Drain system
        connection: local
        become: false
        command: "kubectl drain {{ node_name }} --force=true --grace-period=120 --timeout=300s --ignore-daemonsets --delete-emptydir-data"
      - name: Restart System
        reboot:
          post_reboot_delay: 5
          pre_reboot_delay: 90
      - name: Waiting for host to stabilize
        pause:
          minutes: 5
      always:
      - name: Uncordon System
        connection: local
        become: false
        command: "kubectl uncordon {{ node_name }}"